services:
  parser:
    build:
      context: ./backend/parser
      dockerfile: Dockerfile
    container_name: parser
    env_file:
       - backend/.env
    volumes:
      - ./backend/parser:/app
    ports:
      - "8001:8001"    # whatever port your FastAPI/Flask app listens on
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8001
    depends_on:
      - ml

  frontend:
    image: nginx:alpine
    container_name: frontend
    depends_on:
      - parser
      - ml
    ports:
      - "3000:80"

      
  ml:
    build:
      context: ./backend/ML
      dockerfile: Dockerfile
    container_name: ml_model
    volumes:
      - ./backend/ML:/app
    ports:
      - "8002:8002"
    command: uvicorn app.ml_main:app --reload --host 0.0.0.0 --port 8002